apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-app-config
  namespace: registration

data:
  DB_HOST: "october-mysql.cr226cycuxh5.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "registration_db"

  APP_HOST: "0.0.0.0"
  APP_PORT: "5000"
  APP_DEBUG: "false"

  AWS_REGION: "ap-south-1"