apiVersion: v1
kind: Secret
metadata:
  name: registration-app-secret
  namespace: registration

type: Opaque

stringData:
  DB_USER: "root"
  DB_PASSWORD: "Persistence2027$"
  SES_SENDER_EMAIL: "harish.harvis@outlook.com"