apiVersion: v1
kind: Secret
metadata:
  name: registration-app-secret
type: Opaque
stringData:
  DB_USER: "registration_user"
  DB_PASSWORD: "replace-with-database-password"
  SES_SENDER_EMAIL: "verified-sender@example.com"
